services:
    api:
        build: .
        container_name: api
        ports:
            - "8000:8000"
        depends_on:
            - redis
            - db
        environment:
            - DATABASE_URL=postgresql://user:password@db/dbname
            - REDIS_URL=redis://redis:6379

    worker:
        build: .
        container_name: worker
        command: rq worker high medium low default --with-scheduler
        depends_on:
            - redis
            - db
        environment:
            - DATABASE_URL=postgresql://user:password@db/dbname
            - REDIS_URL=redis://redis:6379
        restart: always

    scheduler:
        build: .
        container_name: scheduler
        command: python -m src.scheduler
        depends_on:
            - redis
            - db
            - api
        environment:
            - DATABASE_URL=postgresql://user:password@db/dbname
            - REDIS_URL=redis://redis:6379

    redis:
        image: "redis:alpine"
        container_name: redis

    db:
        image: "postgres:16"
        container_name: db
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=dbname
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
